"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 100
right_format = """$cmd_duration"""
continuation_prompt = "â–¶â–¶"

[character]
success_symbol= "[î©±](bold green)"
error_symbol = "[ó°…™](bold red)"
vimcmd_symbol = "[ï€“](bold blue)"

[username]
style_user = "bold dimmed blue"
style_root = "bold dimmed black"
format = "[$user]($style) "
disabled = false

[cmd_duration]
format = "[$duration]($style) "

### ICONS ###

# Git Icons
[git_branch]
symbol = "ï˜ "
[git_status]
conflicted = "ó°‡ "
ahead = "ó°‘® ${count} "
behind = "ğŸ¢ ${count} "
diverged = "ó°™ ó°‘® ${ahead_count} ğŸ¢ ${behind_count} "
untracked = "ó° ${count} "
stashed = "ğŸ“¦ ${count} "
modified = "ğŸ“${count} "
staged = "ï‘– ${count} "
renamed = "ó°” ${count} "
deleted= "ó°†´ ${count} "
format = "$all_status$ahead_behind"
style = "bright-white"
[git_commit]
tag_symbol = "ï€¬  "
[git_state]
cherry_pick = "ğŸ’ PICKING (bold red)"

# Coding Icons
[c]
symbol = "î˜ "
[conda]
symbol = "ï„Œ "
[dart]
symbol = "î˜ "
[elixir]
symbol = "î‰µ "
[golang]
symbol = "î˜§ "
[haskell]
symbol = "î· "
[java]
symbol = "î‰– "
[nodejs]
symbol = "îœ˜ "
[package]
symbol = "î¬© "
[python]
symbol = "îˆµ "
[rust]
symbol = "î¨ "

# Other Icons
[directory]
read_only = "ï‘¹ "
[docker_context]
symbol = "ïŒˆ "

