"$schema" = 'https://starship.rs/config-schema.json'

format = """$all"""
right_format = """$cmd_duration"""
continuation_prompt = "â–¶â–¶"

[character]
success_symbol= "[î©±](bold green)"
error_symbol = "[ó°…™](bold red)"
vimcmd_symbol = "[ï€“](bold blue)"

[username]
style_user = "bold dimmed blue"
style_root = "bold dimmed black"
format = "[$user]($style) "
disabled = false

[cmd_duration]
format = "[$duration]($style) "

# Icons
[aws]
symbol = "îŒ½  "
[[battery.display]]
charging_symbol = "âš¡ï¸"
threshold = 20
style = "yellow dimmed"
[buf]
symbol = "ï’ "
[c]
symbol = "î˜ "
[conda]
symbol = "ï„Œ "
[dart]
symbol = "î˜ "
[directory]
read_only = "ï‘¹ "
[docker_context]
symbol = "ïŒˆ "
[elixir]
symbol = "î‰µ "
[elm]
symbol = "î˜¬ "
[git_branch]
symbol = "ï˜ "
[git_status]
conflicted = "ó°‡ "
ahead = "ó°‘® ${count} "
behind = "ğŸ¢ ${count} "
diverged = "ó°™ ó°‘® ${ahead_count} ğŸ¢ ${behind_count} "
untracked = "ó° ${count} "
stashed = "ğŸ“¦ ${count} "
modified = "ğŸ“${count} "
staged = "ï‘– ${count} "
renamed = "ïƒ¬ ${count} "
deleted= "ó°†´ ${count} "
format = "$all_status$ahead_behind"
style = "bright-white"
[git_commit]
tag_symbol = "ï€¬  "
[git_state]
cherry_pick = "ğŸ’ PICKING (bold red)"
[golang]
symbol = "î˜§ "
[haskell]
symbol = "î· "
[hg_branch]
symbol = "ï˜ "
[java]
symbol = "î‰– "
[julia]
symbol = "î˜¤ "
[memory_usage]
symbol = "ï¡š "
[nim]
symbol = "ïš¤ "
[nix_shell]
symbol = "ï‹œ "
[nodejs]
symbol = "îœ˜ "
[package]
symbol = "ï£– "
[python]
symbol = "îˆµ "
[spack]
symbol = "ğŸ…¢ "
[rust]
symbol = "î¨ "
